package com.me.plugin.templates.modity;

import static org.objectweb.asm.Opcodes.*;

import org.objectweb.asm.Label;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;

public class Template18 {

    public static void  modifyFromCode(MethodVisitor methodVisitor,int index){
        Label label0 = new Label();
        methodVisitor.visitLabel(label0);
        methodVisitor.visitLineNumber(88, label0);
        methodVisitor.visitMethodInsn(INVOKESTATIC, "java/nio/charset/Charset", "defaultCharset", "()Ljava/nio/charset/Charset;", false);
        methodVisitor.visitMethodInsn(INVOKESTATIC, "java/lang/System", "identityHashCode", "(Ljava/lang/Object;)I", false);
        methodVisitor.visitInsn(I2L);
        methodVisitor.visitMethodInsn(INVOKESTATIC, "java/lang/System", "nanoTime", "()J", false);
        methodVisitor.visitInsn(LAND);
        methodVisitor.visitInsn(LCONST_0);
        methodVisitor.visitInsn(LCMP);
        Label label1 = new Label();
        methodVisitor.visitJumpInsn(IFNE, label1);
        Label label2 = new Label();
        methodVisitor.visitLabel(label2);
        methodVisitor.visitLineNumber(89, label2);
        methodVisitor.visitTypeInsn(NEW, "java/util/Random");
        methodVisitor.visitInsn(DUP);
        methodVisitor.visitMethodInsn(INVOKESPECIAL, "java/util/Random", "<init>", "()V", false);

        int v1 = ++index;
        methodVisitor.visitVarInsn(ASTORE, v1);
        Label label3 = new Label();
        methodVisitor.visitLabel(label3);
        methodVisitor.visitLineNumber(90, label3);
        methodVisitor.visitVarInsn(ALOAD, v1);
        methodVisitor.visitIntInsn(BIPUSH, 7);
        methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "java/util/Random", "nextInt", "(I)I", false);
        methodVisitor.visitInsn(ICONST_3);
        methodVisitor.visitInsn(IADD);

        int v2 = ++index;
        methodVisitor.visitVarInsn(ISTORE, v2);
        Label label4 = new Label();
        methodVisitor.visitLabel(label4);
        methodVisitor.visitLineNumber(91, label4);
        methodVisitor.visitTypeInsn(NEW, "java/util/Random");
        methodVisitor.visitInsn(DUP);
        methodVisitor.visitMethodInsn(INVOKESPECIAL, "java/util/Random", "<init>", "()V", false);

        int v3 = ++index;
        methodVisitor.visitVarInsn(ASTORE, v3);
        Label label5 = new Label();
        methodVisitor.visitLabel(label5);
        methodVisitor.visitLineNumber(92, label5);
        methodVisitor.visitLdcInsn("abcdefghijklmnopqrstuvwxyz");

        int v4 = ++index;
        methodVisitor.visitVarInsn(ASTORE, v4);
        Label label6 = new Label();
        methodVisitor.visitLabel(label6);
        methodVisitor.visitLineNumber(93, label6);
        methodVisitor.visitTypeInsn(NEW, "java/lang/StringBuilder");
        methodVisitor.visitInsn(DUP);
        methodVisitor.visitMethodInsn(INVOKESPECIAL, "java/lang/StringBuilder", "<init>", "()V", false);

        int v5 = ++index;
        methodVisitor.visitVarInsn(ASTORE, v5);
        Label label7 = new Label();
        methodVisitor.visitLabel(label7);
        methodVisitor.visitLineNumber(94, label7);
        methodVisitor.visitInsn(ICONST_0);

        int v6 = ++index;
        methodVisitor.visitVarInsn(ISTORE, v6);
        Label label8 = new Label();
        methodVisitor.visitLabel(label8);
        methodVisitor.visitVarInsn(ILOAD, v6);
        methodVisitor.visitVarInsn(ILOAD, v2);
        Label label9 = new Label();
        methodVisitor.visitJumpInsn(IF_ICMPGE, label9);
        Label label10 = new Label();
        methodVisitor.visitLabel(label10);
        methodVisitor.visitLineNumber(95, label10);
        methodVisitor.visitVarInsn(ALOAD, v3);
        methodVisitor.visitIntInsn(BIPUSH, 26);
        methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "java/util/Random", "nextInt", "(I)I", false);

        int v7 = ++index;
        methodVisitor.visitVarInsn(ISTORE, v7);
        Label label11 = new Label();
        methodVisitor.visitLabel(label11);
        methodVisitor.visitLineNumber(96, label11);
        methodVisitor.visitVarInsn(ALOAD, v5);
        methodVisitor.visitVarInsn(ALOAD, v4);
        methodVisitor.visitVarInsn(ILOAD, v7);
        methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "java/lang/String", "charAt", "(I)C", false);
        methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "java/lang/StringBuilder", "append", "(C)Ljava/lang/StringBuilder;", false);
        methodVisitor.visitInsn(POP);
        Label label12 = new Label();
        methodVisitor.visitLabel(label12);
        methodVisitor.visitLineNumber(94, label12);
        methodVisitor.visitIincInsn(v6, v1);
        methodVisitor.visitJumpInsn(GOTO, label8);
        methodVisitor.visitLabel(label9);
        methodVisitor.visitLineNumber(99, label9);
        methodVisitor.visitTypeInsn(NEW, "java/lang/StringBuffer");
        methodVisitor.visitInsn(DUP);
        methodVisitor.visitMethodInsn(INVOKESPECIAL, "java/lang/StringBuffer", "<init>", "()V", false);
        methodVisitor.visitVarInsn(ASTORE, v6);
        Label label13 = new Label();
        methodVisitor.visitLabel(label13);
        methodVisitor.visitLineNumber(100, label13);
        methodVisitor.visitVarInsn(ALOAD, v5);
        methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "java/lang/StringBuilder", "toString", "()Ljava/lang/String;", false);
        methodVisitor.visitVarInsn(ASTORE, v7);
        Label label14 = new Label();
        methodVisitor.visitLabel(label14);
        methodVisitor.visitLineNumber(101, label14);
        methodVisitor.visitInsn(ICONST_0);

        int v8 = ++index;
        methodVisitor.visitVarInsn(ISTORE, v8);
        Label label15 = new Label();
        methodVisitor.visitLabel(label15);
        methodVisitor.visitLineNumber(102, label15);
        methodVisitor.visitInsn(ICONST_0);

        int v9 = ++index;
        methodVisitor.visitVarInsn(ISTORE, v9);
        Label label16 = new Label();
        methodVisitor.visitLabel(label16);
        methodVisitor.visitLineNumber(103, label16);
        methodVisitor.visitInsn(ICONST_0);

        int v10 = ++index;
        methodVisitor.visitVarInsn(ISTORE, v10);
        Label label17 = new Label();
        methodVisitor.visitLabel(label17);
        methodVisitor.visitLineNumber(104, label17);
        methodVisitor.visitInsn(ICONST_M1);

        int v11 = ++index;
        methodVisitor.visitVarInsn(ISTORE, v11);
        Label label18 = new Label();
        methodVisitor.visitLabel(label18);
        methodVisitor.visitLineNumber(106, label18);
        methodVisitor.visitInsn(ICONST_0);

        int v12 = ++index;
        methodVisitor.visitVarInsn(ISTORE, v12);
        Label label19 = new Label();
        methodVisitor.visitLabel(label19);
        methodVisitor.visitVarInsn(ILOAD, v12);
        methodVisitor.visitVarInsn(ALOAD, v7);
        methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "java/lang/String", "length", "()I", false);
        Label label20 = new Label();
        methodVisitor.visitJumpInsn(IF_ICMPGE, label20);
        Label label21 = new Label();
        methodVisitor.visitLabel(label21);
        methodVisitor.visitLineNumber(107, label21);
        methodVisitor.visitVarInsn(ALOAD, v7);
        methodVisitor.visitVarInsn(ILOAD, v12);
        methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "java/lang/String", "charAt", "(I)C", false);

        int v13 = ++index;
        methodVisitor.visitVarInsn(ISTORE, v13);
        Label label22 = new Label();
        methodVisitor.visitLabel(label22);
        methodVisitor.visitLineNumber(108, label22);
        methodVisitor.visitVarInsn(ILOAD, v13);
        methodVisitor.visitIntInsn(BIPUSH, 92);
        Label label23 = new Label();
        methodVisitor.visitJumpInsn(IF_ICMPNE, label23);
        methodVisitor.visitVarInsn(ILOAD, v8);
        methodVisitor.visitJumpInsn(IFNE, label23);
        Label label24 = new Label();
        methodVisitor.visitLabel(label24);
        methodVisitor.visitLineNumber(109, label24);
        methodVisitor.visitInsn(ICONST_1);
        methodVisitor.visitVarInsn(ISTORE, v8);
        Label label25 = new Label();
        methodVisitor.visitJumpInsn(GOTO, label25);
        methodVisitor.visitLabel(label23);
        methodVisitor.visitLineNumber(110, label23);
        methodVisitor.visitVarInsn(ILOAD, v13);
        methodVisitor.visitIntInsn(BIPUSH, 36);
        Label label26 = new Label();
        methodVisitor.visitJumpInsn(IF_ICMPNE, label26);
        methodVisitor.visitVarInsn(ILOAD, v8);
        methodVisitor.visitJumpInsn(IFNE, label26);
        Label label27 = new Label();
        methodVisitor.visitLabel(label27);
        methodVisitor.visitLineNumber(111, label27);
        methodVisitor.visitInsn(ICONST_1);
        methodVisitor.visitVarInsn(ISTORE, v9);
        methodVisitor.visitJumpInsn(GOTO, label25);
        methodVisitor.visitLabel(label26);
        methodVisitor.visitLineNumber(112, label26);
        methodVisitor.visitVarInsn(ILOAD, v13);
        methodVisitor.visitIntInsn(BIPUSH, 48);
        Label label28 = new Label();
        methodVisitor.visitJumpInsn(IF_ICMPLT, label28);
        methodVisitor.visitVarInsn(ILOAD, v13);
        methodVisitor.visitIntInsn(BIPUSH, 57);
        methodVisitor.visitJumpInsn(IF_ICMPGT, label28);
        methodVisitor.visitVarInsn(ILOAD, v9);
        methodVisitor.visitJumpInsn(IFEQ, label28);
        methodVisitor.visitVarInsn(ILOAD, v10);
        methodVisitor.visitJumpInsn(IFNE, label28);
        Label label29 = new Label();
        methodVisitor.visitLabel(label29);
        methodVisitor.visitLineNumber(113, label29);
        methodVisitor.visitLdcInsn("a");

        int v14 = ++index;
        methodVisitor.visitVarInsn(ASTORE,v14);
        Label label30 = new Label();
        methodVisitor.visitLabel(label30);
        methodVisitor.visitLineNumber(114, label30);
        methodVisitor.visitVarInsn(ALOAD, v6);
        methodVisitor.visitVarInsn(ALOAD,v14);
        methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "java/lang/StringBuffer", "append", "(Ljava/lang/String;)Ljava/lang/StringBuffer;", false);
        methodVisitor.visitInsn(POP);
        Label label31 = new Label();
        methodVisitor.visitLabel(label31);
        methodVisitor.visitLineNumber(115, label31);
        methodVisitor.visitInsn(ICONST_0);
        methodVisitor.visitVarInsn(ISTORE, v9);
        Label label32 = new Label();
        methodVisitor.visitLabel(label32);
        methodVisitor.visitLineNumber(116, label32);
        methodVisitor.visitJumpInsn(GOTO, label25);
        methodVisitor.visitLabel(label28);
        methodVisitor.visitVarInsn(ILOAD, v13);
        methodVisitor.visitIntInsn(BIPUSH, 123);
        Label label33 = new Label();
        methodVisitor.visitJumpInsn(IF_ICMPNE, label33);
        methodVisitor.visitVarInsn(ILOAD, v9);
        methodVisitor.visitJumpInsn(IFEQ, label33);
        Label label34 = new Label();
        methodVisitor.visitLabel(label34);
        methodVisitor.visitLineNumber(117, label34);
        methodVisitor.visitInsn(ICONST_1);
        methodVisitor.visitVarInsn(ISTORE, v10);
        Label label35 = new Label();
        methodVisitor.visitLabel(label35);
        methodVisitor.visitLineNumber(118, label35);
        methodVisitor.visitVarInsn(ILOAD, v12);
        methodVisitor.visitVarInsn(ISTORE, v11);
        methodVisitor.visitJumpInsn(GOTO, label25);
        methodVisitor.visitLabel(label33);
        methodVisitor.visitLineNumber(119, label33);
        methodVisitor.visitVarInsn(ILOAD, v13);
        methodVisitor.visitIntInsn(BIPUSH, 125);
        Label label36 = new Label();
        methodVisitor.visitJumpInsn(IF_ICMPNE, label36);
        methodVisitor.visitVarInsn(ILOAD, v9);
        methodVisitor.visitJumpInsn(IFEQ, label36);
        methodVisitor.visitVarInsn(ILOAD, v10);
        methodVisitor.visitJumpInsn(IFEQ, label36);
        Label label37 = new Label();
        methodVisitor.visitLabel(label37);
        methodVisitor.visitLineNumber(120, label37);
        methodVisitor.visitLdcInsn("b");
        methodVisitor.visitVarInsn(ASTORE,v14);
        Label label38 = new Label();
        methodVisitor.visitLabel(label38);
        methodVisitor.visitLineNumber(121, label38);
        methodVisitor.visitVarInsn(ALOAD, v6);
        methodVisitor.visitVarInsn(ALOAD,v14);
        methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "java/lang/StringBuffer", "append", "(Ljava/lang/String;)Ljava/lang/StringBuffer;", false);
        methodVisitor.visitInsn(POP);
        Label label39 = new Label();
        methodVisitor.visitLabel(label39);
        methodVisitor.visitLineNumber(122, label39);
        methodVisitor.visitInsn(ICONST_0);
        methodVisitor.visitVarInsn(ISTORE, v9);
        Label label40 = new Label();
        methodVisitor.visitLabel(label40);
        methodVisitor.visitLineNumber(123, label40);
        methodVisitor.visitInsn(ICONST_0);
        methodVisitor.visitVarInsn(ISTORE, v10);
        Label label41 = new Label();
        methodVisitor.visitLabel(label41);
        methodVisitor.visitLineNumber(124, label41);
        methodVisitor.visitJumpInsn(GOTO, label25);
        methodVisitor.visitLabel(label36);
        methodVisitor.visitVarInsn(ILOAD, v13);
        methodVisitor.visitIntInsn(BIPUSH, 125);
        Label label42 = new Label();
        methodVisitor.visitJumpInsn(IF_ICMPEQ, label42);
        methodVisitor.visitVarInsn(ILOAD, v9);
        methodVisitor.visitJumpInsn(IFEQ, label42);
        methodVisitor.visitVarInsn(ILOAD, v10);
        methodVisitor.visitJumpInsn(IFEQ, label42);
        methodVisitor.visitJumpInsn(GOTO, label25);
        methodVisitor.visitLabel(label42);
        methodVisitor.visitLineNumber(126, label42);
        methodVisitor.visitVarInsn(ALOAD, v6);
        methodVisitor.visitVarInsn(ILOAD, v13);
        methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "java/lang/StringBuffer", "append", "(C)Ljava/lang/StringBuffer;", false);
        methodVisitor.visitInsn(POP);
        Label label43 = new Label();
        methodVisitor.visitLabel(label43);
        methodVisitor.visitLineNumber(127, label43);
        methodVisitor.visitInsn(ICONST_0);
        methodVisitor.visitVarInsn(ISTORE, v9);
        Label label44 = new Label();
        methodVisitor.visitLabel(label44);
        methodVisitor.visitLineNumber(128, label44);
        methodVisitor.visitInsn(ICONST_0);
        methodVisitor.visitVarInsn(ISTORE, v8);
        Label label45 = new Label();
        methodVisitor.visitLabel(label45);
        methodVisitor.visitLineNumber(129, label45);
        methodVisitor.visitInsn(ICONST_0);
        methodVisitor.visitVarInsn(ISTORE, v10);
        methodVisitor.visitLabel(label25);
        methodVisitor.visitLineNumber(106, label25);
        methodVisitor.visitIincInsn(v12, v1);
        methodVisitor.visitJumpInsn(GOTO, label19);
        methodVisitor.visitLabel(label20);
        methodVisitor.visitLineNumber(133, label20);
        methodVisitor.visitVarInsn(ILOAD, v8);
        Label label46 = new Label();
        methodVisitor.visitJumpInsn(IFEQ, label46);
        Label label47 = new Label();
        methodVisitor.visitLabel(label47);
        methodVisitor.visitLineNumber(134, label47);
        methodVisitor.visitTypeInsn(NEW, "java/lang/IllegalArgumentException");
        methodVisitor.visitInsn(DUP);
        methodVisitor.visitLdcInsn("character to be escaped is missing");
        methodVisitor.visitMethodInsn(INVOKESPECIAL, "java/lang/IllegalArgumentException", "<init>", "(Ljava/lang/String;)V", false);
        methodVisitor.visitInsn(ATHROW);
        methodVisitor.visitLabel(label46);
        methodVisitor.visitLineNumber(137, label46);
        methodVisitor.visitVarInsn(ILOAD, v9);
        Label label48 = new Label();
        methodVisitor.visitJumpInsn(IFEQ, label48);
        Label label49 = new Label();
        methodVisitor.visitLabel(label49);
        methodVisitor.visitLineNumber(138, label49);
        methodVisitor.visitTypeInsn(NEW, "java/lang/IllegalArgumentException");
        methodVisitor.visitInsn(DUP);
        methodVisitor.visitLdcInsn("Illegal group reference: group index is missing");
        methodVisitor.visitMethodInsn(INVOKESPECIAL, "java/lang/IllegalArgumentException", "<init>", "(Ljava/lang/String;)V", false);
        methodVisitor.visitInsn(ATHROW);
        methodVisitor.visitLabel(label48);
        methodVisitor.visitLineNumber(141, label48);
        methodVisitor.visitVarInsn(ILOAD, v10);
        methodVisitor.visitJumpInsn(IFEQ, label1);
        Label label50 = new Label();
        methodVisitor.visitLabel(label50);
        methodVisitor.visitLineNumber(142, label50);
        methodVisitor.visitTypeInsn(NEW, "java/lang/IllegalArgumentException");
        methodVisitor.visitInsn(DUP);
        methodVisitor.visitLdcInsn("Missing ending brace '}' from replacement string");
        methodVisitor.visitMethodInsn(INVOKESPECIAL, "java/lang/IllegalArgumentException", "<init>", "(Ljava/lang/String;)V", false);
        methodVisitor.visitInsn(ATHROW);
        methodVisitor.visitLabel(label1);
        methodVisitor.visitLineNumber(145, label1);

    }
}
