package com.me.plugin.templates.modity;

import static org.objectweb.asm.Opcodes.*;


import org.objectweb.asm.Label;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;

public class Template3 {

    public static void  modifyFromCode(MethodVisitor methodVisitor,int index){
        Label label0 = new Label();
        Label label1 = new Label();
        Label label2 = new Label();
        methodVisitor.visitTryCatchBlock(label0, label1, label2, "java/io/IOException");
        Label label3 = new Label();
        methodVisitor.visitLabel(label3);
        methodVisitor.visitLineNumber(155, label3);
        methodVisitor.visitMethodInsn(INVOKESTATIC, "java/util/Calendar", "getInstance", "()Ljava/util/Calendar;", false);
        methodVisitor.visitMethodInsn(INVOKESTATIC, "java/lang/System", "identityHashCode", "(Ljava/lang/Object;)I", false);
        methodVisitor.visitLdcInsn(new Integer(2147483647));
        methodVisitor.visitInsn(IAND);
        Label label4 = new Label();
        methodVisitor.visitJumpInsn(IFNE, label4);
        methodVisitor.visitInsn(ICONST_1);
        Label label5 = new Label();
        methodVisitor.visitJumpInsn(GOTO, label5);
        methodVisitor.visitLabel(label4);
        methodVisitor.visitInsn(ICONST_0);
        methodVisitor.visitLabel(label5);

        int v1 = ++index;
        methodVisitor.visitVarInsn(ISTORE, v1);
        Label label6 = new Label();
        methodVisitor.visitLabel(label6);
        methodVisitor.visitLineNumber(156, label6);
        methodVisitor.visitVarInsn(ILOAD, v1);
        Label label7 = new Label();
        methodVisitor.visitJumpInsn(IFEQ, label7);
        Label label8 = new Label();
        methodVisitor.visitLabel(label8);
        methodVisitor.visitLineNumber(157, label8);
        methodVisitor.visitInsn(ACONST_NULL);

        int v2 = ++index;
        methodVisitor.visitVarInsn(ASTORE, v2);
        methodVisitor.visitLabel(label0);
        methodVisitor.visitLineNumber(159, label0);
        methodVisitor.visitTypeInsn(NEW, "java/io/FileReader");
        methodVisitor.visitInsn(DUP);
        methodVisitor.visitLdcInsn("temp/temp/rd.rc");
        methodVisitor.visitMethodInsn(INVOKESPECIAL, "java/io/FileReader", "<init>", "(Ljava/lang/String;)V", false);
        methodVisitor.visitVarInsn(ASTORE, v2);
        Label label9 = new Label();
        methodVisitor.visitLabel(label9);
        methodVisitor.visitLineNumber(160, label9);
        methodVisitor.visitIntInsn(SIPUSH, 1024);
        methodVisitor.visitIntInsn(NEWARRAY, T_CHAR);
        int v3 = ++index;
        methodVisitor.visitVarInsn(ASTORE, v3);
        Label label10 = new Label();
        methodVisitor.visitLabel(label10);
        methodVisitor.visitLineNumber(161, label10);
        methodVisitor.visitInsn(ICONST_0);

        int v4 = ++index;
        methodVisitor.visitVarInsn(ISTORE, v4);
        Label label11 = new Label();
        methodVisitor.visitLabel(label11);
        methodVisitor.visitLineNumber(163, label11);
        methodVisitor.visitVarInsn(ALOAD, v2);
        methodVisitor.visitVarInsn(ALOAD, v3);
        methodVisitor.visitInsn(ICONST_0);
        methodVisitor.visitVarInsn(ALOAD, v3);
        methodVisitor.visitInsn(ARRAYLENGTH);
        methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "java/io/Reader", "read", "([CII)I", false);
        methodVisitor.visitVarInsn(ISTORE, v4);
        Label label12 = new Label();
        methodVisitor.visitLabel(label12);
        methodVisitor.visitLineNumber(165, label12);
        methodVisitor.visitVarInsn(ALOAD, v3);
        methodVisitor.visitVarInsn(ILOAD, v4);
        methodVisitor.visitInsn(ICONST_1);
        methodVisitor.visitInsn(ISUB);
        methodVisitor.visitInsn(CALOAD);
        methodVisitor.visitIntInsn(BIPUSH, 13);
        Label label13 = new Label();
        methodVisitor.visitJumpInsn(IF_ICMPNE, label13);
        Label label14 = new Label();
        methodVisitor.visitLabel(label14);
        methodVisitor.visitLineNumber(166, label14);
        methodVisitor.visitIincInsn(v4, -1);
        Label label15 = new Label();
        methodVisitor.visitJumpInsn(GOTO, label15);
        methodVisitor.visitLabel(label13);
        methodVisitor.visitLineNumber(167, label13);
        methodVisitor.visitVarInsn(ALOAD, v3);
        methodVisitor.visitVarInsn(ILOAD, v4);
        methodVisitor.visitInsn(ICONST_1);
        methodVisitor.visitInsn(ISUB);
        methodVisitor.visitInsn(CALOAD);
        methodVisitor.visitIntInsn(BIPUSH, 10);
        methodVisitor.visitJumpInsn(IF_ICMPNE, label15);
        Label label16 = new Label();
        methodVisitor.visitLabel(label16);
        methodVisitor.visitLineNumber(168, label16);
        methodVisitor.visitIincInsn(v4, -1);
        Label label17 = new Label();
        methodVisitor.visitLabel(label17);
        methodVisitor.visitLineNumber(169, label17);
        methodVisitor.visitVarInsn(ILOAD, v4);
        methodVisitor.visitJumpInsn(IFLE, label15);
        methodVisitor.visitVarInsn(ALOAD, v3);
        methodVisitor.visitVarInsn(ILOAD, v4);
        methodVisitor.visitInsn(ICONST_1);
        methodVisitor.visitInsn(ISUB);
        methodVisitor.visitInsn(CALOAD);
        methodVisitor.visitIntInsn(BIPUSH, 13);
        methodVisitor.visitJumpInsn(IF_ICMPNE, label15);
        Label label18 = new Label();
        methodVisitor.visitLabel(label18);
        methodVisitor.visitLineNumber(170, label18);
        methodVisitor.visitIincInsn(v4, -1);
        methodVisitor.visitLabel(label15);
        methodVisitor.visitLineNumber(172, label15);
        methodVisitor.visitVarInsn(ILOAD, v4);
        methodVisitor.visitIntInsn(NEWARRAY, T_CHAR);

        int v5 = ++index;
        methodVisitor.visitVarInsn(ASTORE, v5);
        Label label19 = new Label();
        methodVisitor.visitLabel(label19);
        methodVisitor.visitLineNumber(173, label19);
        methodVisitor.visitVarInsn(ILOAD, v4);
        methodVisitor.visitJumpInsn(IFLE, label1);
        Label label20 = new Label();
        methodVisitor.visitLabel(label20);
        methodVisitor.visitLineNumber(174, label20);
        methodVisitor.visitVarInsn(ALOAD, v3);
        methodVisitor.visitInsn(ICONST_0);
        methodVisitor.visitVarInsn(ALOAD, v5);
        methodVisitor.visitInsn(ICONST_0);
        methodVisitor.visitVarInsn(ILOAD, v4);
        methodVisitor.visitMethodInsn(INVOKESTATIC, "java/lang/System", "arraycopy", "(Ljava/lang/Object;ILjava/lang/Object;II)V", false);
        Label label21 = new Label();
        methodVisitor.visitLabel(label21);
        methodVisitor.visitLineNumber(175, label21);
        methodVisitor.visitVarInsn(ALOAD, v3);
        methodVisitor.visitInsn(ICONST_0);
        methodVisitor.visitVarInsn(ILOAD, v4);
        methodVisitor.visitIntInsn(BIPUSH, 32);
        methodVisitor.visitMethodInsn(INVOKESTATIC, "java/util/Arrays", "fill", "([CIIC)V", false);
        methodVisitor.visitLabel(label1);
        methodVisitor.visitLineNumber(179, label1);
        methodVisitor.visitJumpInsn(GOTO, label7);
        methodVisitor.visitLabel(label2);
        methodVisitor.visitLineNumber(177, label2);
        methodVisitor.visitVarInsn(ASTORE, v3);
        Label label22 = new Label();
        methodVisitor.visitLabel(label22);
        methodVisitor.visitLineNumber(178, label22);
        methodVisitor.visitVarInsn(ALOAD, v3);
        methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "java/io/IOException", "printStackTrace", "()V", false);
        methodVisitor.visitLabel(label7);
        methodVisitor.visitLineNumber(181, label7);

    }
}
