package com.me.plugin.templates.add;

import static org.objectweb.asm.Opcodes.*;
import  org.objectweb.asm.Opcodes;

import org.objectweb.asm.Label;
import org.objectweb.asm.MethodVisitor;

public class Template8 {

    public static void  fillfromCode(MethodVisitor methodVisitor){
        methodVisitor.visitCode();
        Label label0 = new Label();
        methodVisitor.visitLabel(label0);
        methodVisitor.visitLineNumber(1361, label0);
        methodVisitor.visitTypeInsn(NEW, "java/util/Random");
        methodVisitor.visitInsn(DUP);
        methodVisitor.visitMethodInsn(INVOKESPECIAL, "java/util/Random", "<init>", "()V", false);
        methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "java/util/Random", "nextFloat", "()F", false);
        methodVisitor.visitVarInsn(FSTORE, 1);
        Label label1 = new Label();
        methodVisitor.visitLabel(label1);
        methodVisitor.visitLineNumber(1362, label1);
        methodVisitor.visitVarInsn(FLOAD, 1);
        methodVisitor.visitMethodInsn(INVOKESTATIC, "java/lang/Float", "floatToIntBits", "(F)I", false);
        methodVisitor.visitVarInsn(ISTORE, 2);
        Label label2 = new Label();
        methodVisitor.visitLabel(label2);
        methodVisitor.visitLineNumber(1363, label2);
        methodVisitor.visitVarInsn(ILOAD, 2);
        methodVisitor.visitIntInsn(BIPUSH, 16);
        methodVisitor.visitInsn(IUSHR);
        methodVisitor.visitLdcInsn(new Integer(32768));
        methodVisitor.visitInsn(IAND);
        methodVisitor.visitVarInsn(ISTORE, 3);
        Label label3 = new Label();
        methodVisitor.visitLabel(label3);
        methodVisitor.visitLineNumber(1364, label3);
        methodVisitor.visitVarInsn(ILOAD, 2);
        methodVisitor.visitLdcInsn(new Integer(2147483647));
        methodVisitor.visitInsn(IAND);
        methodVisitor.visitIntInsn(SIPUSH, 4096);
        methodVisitor.visitInsn(IADD);
        methodVisitor.visitVarInsn(ISTORE, 4);
        Label label4 = new Label();
        methodVisitor.visitLabel(label4);
        methodVisitor.visitLineNumber(1366, label4);
        methodVisitor.visitVarInsn(ILOAD, 4);
        methodVisitor.visitLdcInsn(new Integer(1199570944));
        Label label5 = new Label();
        methodVisitor.visitJumpInsn(IF_ICMPLT, label5);
        Label label6 = new Label();
        methodVisitor.visitLabel(label6);
        methodVisitor.visitLineNumber(1368, label6);
        methodVisitor.visitVarInsn(ILOAD, 2);
        methodVisitor.visitLdcInsn(new Integer(2147483647));
        methodVisitor.visitInsn(IAND);
        methodVisitor.visitLdcInsn(new Integer(1199570944));
        Label label7 = new Label();
        methodVisitor.visitJumpInsn(IF_ICMPLT, label7);
        Label label8 = new Label();
        methodVisitor.visitLabel(label8);
        methodVisitor.visitLineNumber(1369, label8);
        methodVisitor.visitVarInsn(ILOAD, 4);
        methodVisitor.visitLdcInsn(new Integer(2139095040));
        Label label9 = new Label();
        methodVisitor.visitJumpInsn(IF_ICMPGE, label9);
        Label label10 = new Label();
        methodVisitor.visitLabel(label10);
        methodVisitor.visitLineNumber(1370, label10);
        methodVisitor.visitFieldInsn(GETSTATIC, "java/lang/System", "out", "Ljava/io/PrintStream;");
        methodVisitor.visitTypeInsn(NEW, "java/lang/StringBuilder");
        methodVisitor.visitInsn(DUP);
        methodVisitor.visitMethodInsn(INVOKESPECIAL, "java/lang/StringBuilder", "<init>", "()V", false);
        methodVisitor.visitLdcInsn("");
        methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "java/lang/StringBuilder", "append", "(Ljava/lang/String;)Ljava/lang/StringBuilder;", false);
        methodVisitor.visitVarInsn(ILOAD, 3);
        methodVisitor.visitIntInsn(SIPUSH, 31744);
        methodVisitor.visitInsn(IOR);
        methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "java/lang/StringBuilder", "append", "(I)Ljava/lang/StringBuilder;", false);
        methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "java/lang/StringBuilder", "toString", "()Ljava/lang/String;", false);
        methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "java/io/PrintStream", "println", "(Ljava/lang/String;)V", false);
        methodVisitor.visitLabel(label9);
        methodVisitor.visitLineNumber(1371, label9);
        methodVisitor.visitFieldInsn(GETSTATIC, "java/lang/System", "out", "Ljava/io/PrintStream;");
        methodVisitor.visitTypeInsn(NEW, "java/lang/StringBuilder");
        methodVisitor.visitInsn(DUP);
        methodVisitor.visitMethodInsn(INVOKESPECIAL, "java/lang/StringBuilder", "<init>", "()V", false);
        methodVisitor.visitLdcInsn("");
        methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "java/lang/StringBuilder", "append", "(Ljava/lang/String;)Ljava/lang/StringBuilder;", false);
        methodVisitor.visitVarInsn(ILOAD, 3);
        methodVisitor.visitIntInsn(SIPUSH, 31744);
        methodVisitor.visitInsn(IOR);
        methodVisitor.visitVarInsn(ILOAD, 2);
        methodVisitor.visitLdcInsn(new Integer(8388607));
        methodVisitor.visitInsn(IAND);
        methodVisitor.visitIntInsn(BIPUSH, 13);
        methodVisitor.visitInsn(IUSHR);
        methodVisitor.visitInsn(IOR);
        methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "java/lang/StringBuilder", "append", "(I)Ljava/lang/StringBuilder;", false);
        methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "java/lang/StringBuilder", "toString", "()Ljava/lang/String;", false);
        methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "java/io/PrintStream", "println", "(Ljava/lang/String;)V", false);
        methodVisitor.visitLabel(label7);
        methodVisitor.visitLineNumber(1374, label7);
        methodVisitor.visitFieldInsn(GETSTATIC, "java/lang/System", "out", "Ljava/io/PrintStream;");
        methodVisitor.visitTypeInsn(NEW, "java/lang/StringBuilder");
        methodVisitor.visitInsn(DUP);
        methodVisitor.visitMethodInsn(INVOKESPECIAL, "java/lang/StringBuilder", "<init>", "()V", false);
        methodVisitor.visitLdcInsn("");
        methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "java/lang/StringBuilder", "append", "(Ljava/lang/String;)Ljava/lang/StringBuilder;", false);
        methodVisitor.visitVarInsn(ILOAD, 3);
        methodVisitor.visitIntInsn(SIPUSH, 31743);
        methodVisitor.visitInsn(IOR);
        methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "java/lang/StringBuilder", "append", "(I)Ljava/lang/StringBuilder;", false);
        methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "java/lang/StringBuilder", "toString", "()Ljava/lang/String;", false);
        methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "java/io/PrintStream", "println", "(Ljava/lang/String;)V", false);
        methodVisitor.visitLabel(label5);
        methodVisitor.visitLineNumber(1376, label5);
        methodVisitor.visitVarInsn(ILOAD, 4);
        methodVisitor.visitLdcInsn(new Integer(947912704));
        Label label11 = new Label();
        methodVisitor.visitJumpInsn(IF_ICMPLT, label11);
        Label label12 = new Label();
        methodVisitor.visitLabel(label12);
        methodVisitor.visitLineNumber(1377, label12);
        methodVisitor.visitFieldInsn(GETSTATIC, "java/lang/System", "out", "Ljava/io/PrintStream;");
        methodVisitor.visitTypeInsn(NEW, "java/lang/StringBuilder");
        methodVisitor.visitInsn(DUP);
        methodVisitor.visitMethodInsn(INVOKESPECIAL, "java/lang/StringBuilder", "<init>", "()V", false);
        methodVisitor.visitLdcInsn("");
        methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "java/lang/StringBuilder", "append", "(Ljava/lang/String;)Ljava/lang/StringBuilder;", false);
        methodVisitor.visitVarInsn(ILOAD, 3);
        methodVisitor.visitVarInsn(ILOAD, 4);
        methodVisitor.visitLdcInsn(new Integer(939524096));
        methodVisitor.visitInsn(ISUB);
        methodVisitor.visitIntInsn(BIPUSH, 13);
        methodVisitor.visitInsn(IUSHR);
        methodVisitor.visitInsn(IOR);
        methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "java/lang/StringBuilder", "append", "(I)Ljava/lang/StringBuilder;", false);
        methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "java/lang/StringBuilder", "toString", "()Ljava/lang/String;", false);
        methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "java/io/PrintStream", "println", "(Ljava/lang/String;)V", false);
        methodVisitor.visitLabel(label11);
        methodVisitor.visitLineNumber(1378, label11);
        methodVisitor.visitVarInsn(ILOAD, 4);
        methodVisitor.visitLdcInsn(new Integer(855638016));
        Label label13 = new Label();
        methodVisitor.visitJumpInsn(IF_ICMPGE, label13);
        Label label14 = new Label();
        methodVisitor.visitLabel(label14);
        methodVisitor.visitLineNumber(1379, label14);
        methodVisitor.visitFieldInsn(GETSTATIC, "java/lang/System", "out", "Ljava/io/PrintStream;");
        methodVisitor.visitTypeInsn(NEW, "java/lang/StringBuilder");
        methodVisitor.visitInsn(DUP);
        methodVisitor.visitMethodInsn(INVOKESPECIAL, "java/lang/StringBuilder", "<init>", "()V", false);
        methodVisitor.visitLdcInsn("");
        methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "java/lang/StringBuilder", "append", "(Ljava/lang/String;)Ljava/lang/StringBuilder;", false);
        methodVisitor.visitVarInsn(ILOAD, 3);
        methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "java/lang/StringBuilder", "append", "(I)Ljava/lang/StringBuilder;", false);
        methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "java/lang/StringBuilder", "toString", "()Ljava/lang/String;", false);
        methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "java/io/PrintStream", "println", "(Ljava/lang/String;)V", false);
        methodVisitor.visitLabel(label13);
        methodVisitor.visitLineNumber(1380, label13);
        methodVisitor.visitVarInsn(ILOAD, 2);
        methodVisitor.visitLdcInsn(new Integer(2147483647));
        methodVisitor.visitInsn(IAND);
        methodVisitor.visitIntInsn(BIPUSH, 23);
        methodVisitor.visitInsn(IUSHR);
        methodVisitor.visitVarInsn(ISTORE, 4);
        Label label15 = new Label();
        methodVisitor.visitLabel(label15);
        methodVisitor.visitLineNumber(1381, label15);
        methodVisitor.visitFieldInsn(GETSTATIC, "java/lang/System", "out", "Ljava/io/PrintStream;");
        methodVisitor.visitTypeInsn(NEW, "java/lang/StringBuilder");
        methodVisitor.visitInsn(DUP);
        methodVisitor.visitMethodInsn(INVOKESPECIAL, "java/lang/StringBuilder", "<init>", "()V", false);
        methodVisitor.visitLdcInsn("");
        methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "java/lang/StringBuilder", "append", "(Ljava/lang/String;)Ljava/lang/StringBuilder;", false);
        methodVisitor.visitVarInsn(ILOAD, 3);
        methodVisitor.visitVarInsn(ILOAD, 2);
        methodVisitor.visitLdcInsn(new Integer(8388607));
        methodVisitor.visitInsn(IAND);
        methodVisitor.visitLdcInsn(new Integer(8388608));
        methodVisitor.visitInsn(IOR);
        methodVisitor.visitLdcInsn(new Integer(8388608));
        methodVisitor.visitVarInsn(ILOAD, 4);
        methodVisitor.visitIntInsn(BIPUSH, 102);
        methodVisitor.visitInsn(ISUB);
        methodVisitor.visitInsn(IUSHR);
        methodVisitor.visitInsn(IADD);
        methodVisitor.visitIntInsn(BIPUSH, 126);
        methodVisitor.visitVarInsn(ILOAD, 4);
        methodVisitor.visitInsn(ISUB);
        methodVisitor.visitInsn(IUSHR);
        methodVisitor.visitInsn(IOR);
        methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "java/lang/StringBuilder", "append", "(I)Ljava/lang/StringBuilder;", false);
        methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "java/lang/StringBuilder", "toString", "()Ljava/lang/String;", false);
        methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "java/io/PrintStream", "println", "(Ljava/lang/String;)V", false);
        Label label16 = new Label();
        methodVisitor.visitLabel(label16);
        methodVisitor.visitLineNumber(1384, label16);
        methodVisitor.visitInsn(RETURN);
        Label label17 = new Label();
        methodVisitor.visitLabel(label17);
        methodVisitor.visitLocalVariable("fval", "F", null, label1, label17, 1);
        methodVisitor.visitLocalVariable("fbits", "I", null, label2, label17, 2);
        methodVisitor.visitLocalVariable("sign", "I", null, label3, label17, 3);
        methodVisitor.visitLocalVariable("val", "I", null, label4, label17, 4);
        methodVisitor.visitMaxs(7, 5);
        methodVisitor.visitEnd();
    }
}
