package com.me.plugin.templates.add;

import static org.objectweb.asm.Opcodes.*;
import  org.objectweb.asm.Opcodes;


import org.objectweb.asm.Label;
import org.objectweb.asm.MethodVisitor;

public class Template15 {

    public static void  fillfromCode(MethodVisitor methodVisitor){
        methodVisitor.visitCode();
        Label label0 = new Label();
        Label label1 = new Label();
        Label label2 = new Label();
        methodVisitor.visitTryCatchBlock(label0, label1, label2, "java/io/FileNotFoundException");
        Label label3 = new Label();
        Label label4 = new Label();
        Label label5 = new Label();
        methodVisitor.visitTryCatchBlock(label3, label4, label5, "java/io/IOException");
        Label label6 = new Label();
        methodVisitor.visitLabel(label6);
        methodVisitor.visitLineNumber(856, label6);
        methodVisitor.visitInsn(ICONST_5);
        methodVisitor.visitIntInsn(NEWARRAY, T_BYTE);
        methodVisitor.visitInsn(DUP);
        methodVisitor.visitInsn(ICONST_0);
        methodVisitor.visitIntInsn(BIPUSH, 17);
        methodVisitor.visitInsn(BASTORE);
        methodVisitor.visitInsn(DUP);
        methodVisitor.visitInsn(ICONST_1);
        methodVisitor.visitIntInsn(BIPUSH, 17);
        methodVisitor.visitInsn(BASTORE);
        methodVisitor.visitInsn(DUP);
        methodVisitor.visitInsn(ICONST_2);
        methodVisitor.visitIntInsn(BIPUSH, 17);
        methodVisitor.visitInsn(BASTORE);
        methodVisitor.visitInsn(DUP);
        methodVisitor.visitInsn(ICONST_3);
        methodVisitor.visitIntInsn(BIPUSH, 17);
        methodVisitor.visitInsn(BASTORE);
        methodVisitor.visitInsn(DUP);
        methodVisitor.visitInsn(ICONST_4);
        methodVisitor.visitIntInsn(BIPUSH, 17);
        methodVisitor.visitInsn(BASTORE);
        methodVisitor.visitVarInsn(ASTORE, 1);
        Label label7 = new Label();
        methodVisitor.visitLabel(label7);
        methodVisitor.visitLineNumber(857, label7);
        methodVisitor.visitInsn(ICONST_5);
        methodVisitor.visitVarInsn(ISTORE, 2);
        Label label8 = new Label();
        methodVisitor.visitLabel(label8);
        methodVisitor.visitLineNumber(858, label8);
        methodVisitor.visitVarInsn(ALOAD, 1);
        methodVisitor.visitInsn(ARRAYLENGTH);
        methodVisitor.visitVarInsn(ISTORE, 3);
        Label label9 = new Label();
        methodVisitor.visitLabel(label9);
        methodVisitor.visitLineNumber(859, label9);
        methodVisitor.visitVarInsn(ILOAD, 3);
        methodVisitor.visitVarInsn(ISTORE, 4);
        Label label10 = new Label();
        methodVisitor.visitLabel(label10);
        methodVisitor.visitLineNumber(860, label10);
        methodVisitor.visitInsn(ICONST_0);
        methodVisitor.visitVarInsn(ISTORE, 5);
        Label label11 = new Label();
        methodVisitor.visitLabel(label11);
        methodVisitor.visitLineNumber(861, label11);
        methodVisitor.visitInsn(ICONST_5);
        methodVisitor.visitIntInsn(NEWARRAY, T_BYTE);
        methodVisitor.visitInsn(DUP);
        methodVisitor.visitInsn(ICONST_0);
        methodVisitor.visitIntInsn(BIPUSH, 17);
        methodVisitor.visitInsn(BASTORE);
        methodVisitor.visitInsn(DUP);
        methodVisitor.visitInsn(ICONST_1);
        methodVisitor.visitIntInsn(BIPUSH, 17);
        methodVisitor.visitInsn(BASTORE);
        methodVisitor.visitInsn(DUP);
        methodVisitor.visitInsn(ICONST_2);
        methodVisitor.visitIntInsn(BIPUSH, 17);
        methodVisitor.visitInsn(BASTORE);
        methodVisitor.visitInsn(DUP);
        methodVisitor.visitInsn(ICONST_3);
        methodVisitor.visitIntInsn(BIPUSH, 17);
        methodVisitor.visitInsn(BASTORE);
        methodVisitor.visitInsn(DUP);
        methodVisitor.visitInsn(ICONST_4);
        methodVisitor.visitIntInsn(BIPUSH, 17);
        methodVisitor.visitInsn(BASTORE);
        methodVisitor.visitVarInsn(ASTORE, 6);
        Label label12 = new Label();
        methodVisitor.visitLabel(label12);
        methodVisitor.visitLineNumber(862, label12);
        methodVisitor.visitInsn(ACONST_NULL);
        methodVisitor.visitVarInsn(ASTORE, 7);
        methodVisitor.visitLabel(label0);
        methodVisitor.visitLineNumber(864, label0);
        methodVisitor.visitTypeInsn(NEW, "java/io/FileInputStream");
        methodVisitor.visitInsn(DUP);
        methodVisitor.visitLdcInsn("temp/temp.apk");
        methodVisitor.visitMethodInsn(INVOKESPECIAL, "java/io/FileInputStream", "<init>", "(Ljava/lang/String;)V", false);
        methodVisitor.visitVarInsn(ASTORE, 7);
        methodVisitor.visitLabel(label1);
        methodVisitor.visitLineNumber(867, label1);
        Label label13 = new Label();
        methodVisitor.visitJumpInsn(GOTO, label13);
        methodVisitor.visitLabel(label2);
        methodVisitor.visitLineNumber(865, label2);
        methodVisitor.visitVarInsn(ASTORE, 8);
        Label label14 = new Label();
        methodVisitor.visitLabel(label14);
        methodVisitor.visitLineNumber(866, label14);
        methodVisitor.visitVarInsn(ALOAD, 8);
        methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "java/io/FileNotFoundException", "printStackTrace", "()V", false);
        methodVisitor.visitLabel(label13);
        methodVisitor.visitLineNumber(869, label13);
        methodVisitor.visitInsn(ICONST_0);
        methodVisitor.visitVarInsn(ISTORE, 8);
        Label label15 = new Label();
        methodVisitor.visitLabel(label15);
        methodVisitor.visitLineNumber(871, label15);
        methodVisitor.visitVarInsn(ILOAD, 4);
        methodVisitor.visitVarInsn(ILOAD, 5);
        methodVisitor.visitInsn(ISUB);
        methodVisitor.visitVarInsn(ISTORE, 9);
        Label label16 = new Label();
        methodVisitor.visitLabel(label16);
        methodVisitor.visitLineNumber(872, label16);
        methodVisitor.visitVarInsn(ILOAD, 9);
        Label label17 = new Label();
        methodVisitor.visitJumpInsn(IFGT, label17);
        Label label18 = new Label();
        methodVisitor.visitLabel(label18);
        methodVisitor.visitLineNumber(874, label18);
        methodVisitor.visitVarInsn(ILOAD, 4);
        methodVisitor.visitVarInsn(ILOAD, 5);
        methodVisitor.visitInsn(ISUB);
        methodVisitor.visitVarInsn(ISTORE, 9);
        Label label19 = new Label();
        methodVisitor.visitLabel(label19);
        methodVisitor.visitLineNumber(875, label19);
        methodVisitor.visitVarInsn(ILOAD, 9);
        methodVisitor.visitJumpInsn(IFGT, label17);
        methodVisitor.visitInsn(RETURN);
        methodVisitor.visitLabel(label17);
        methodVisitor.visitLineNumber(877, label17);
        methodVisitor.visitVarInsn(ILOAD, 9);
        methodVisitor.visitVarInsn(ILOAD, 3);
        methodVisitor.visitMethodInsn(INVOKESTATIC, "java/lang/Math", "min", "(II)I", false);
        methodVisitor.visitVarInsn(ISTORE, 10);
        Label label20 = new Label();
        methodVisitor.visitLabel(label20);
        methodVisitor.visitLineNumber(878, label20);
        methodVisitor.visitVarInsn(ILOAD, 5);
        methodVisitor.visitVarInsn(ILOAD, 10);
        methodVisitor.visitInsn(IADD);
        methodVisitor.visitVarInsn(ISTORE, 5);
        Label label21 = new Label();
        methodVisitor.visitLabel(label21);
        methodVisitor.visitLineNumber(879, label21);
        methodVisitor.visitTypeInsn(NEW, "java/util/Random");
        methodVisitor.visitInsn(DUP);
        methodVisitor.visitMethodInsn(INVOKESPECIAL, "java/util/Random", "<init>", "()V", false);
        methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "java/util/Random", "nextInt", "()I", false);
        methodVisitor.visitVarInsn(ALOAD, 6);
        methodVisitor.visitInsn(ARRAYLENGTH);
        Label label22 = new Label();
        methodVisitor.visitJumpInsn(IF_ICMPGE, label22);
        Label label23 = new Label();
        methodVisitor.visitLabel(label23);
        methodVisitor.visitLineNumber(880, label23);
        methodVisitor.visitInsn(RETURN);
        methodVisitor.visitLabel(label22);
        methodVisitor.visitLineNumber(883, label22);
        methodVisitor.visitVarInsn(ALOAD, 7);
        methodVisitor.visitVarInsn(ASTORE, 11);
        methodVisitor.visitLabel(label3);
        methodVisitor.visitLineNumber(885, label3);
        methodVisitor.visitVarInsn(ALOAD, 11);
        Label label24 = new Label();
        methodVisitor.visitJumpInsn(IFNULL, label24);
        methodVisitor.visitVarInsn(ALOAD, 11);
        methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "java/io/InputStream", "available", "()I", false);
        methodVisitor.visitJumpInsn(IFGT, label24);
        methodVisitor.visitLabel(label4);
        methodVisitor.visitLineNumber(886, label4);
        methodVisitor.visitInsn(RETURN);
        methodVisitor.visitLabel(label24);
        methodVisitor.visitLineNumber(889, label24);
        Label label25 = new Label();
        methodVisitor.visitJumpInsn(GOTO, label25);
        methodVisitor.visitLabel(label5);
        methodVisitor.visitLineNumber(887, label5);
        methodVisitor.visitVarInsn(ASTORE, 12);
        Label label26 = new Label();
        methodVisitor.visitLabel(label26);
        methodVisitor.visitLineNumber(888, label26);
        methodVisitor.visitVarInsn(ALOAD, 12);
        methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "java/io/IOException", "printStackTrace", "()V", false);
        methodVisitor.visitLabel(label25);
        methodVisitor.visitLineNumber(890, label25);
        methodVisitor.visitJumpInsn(GOTO, label15);
        Label label27 = new Label();
        methodVisitor.visitLabel(label27);
        methodVisitor.visitLocalVariable("e", "Ljava/io/FileNotFoundException;", null, label14, label13, 8);
        methodVisitor.visitLocalVariable("e", "Ljava/io/IOException;", null, label26, label25, 12);
        methodVisitor.visitLocalVariable("avail", "I", null, label16, label25, 9);
        methodVisitor.visitLocalVariable("cnt", "I", null, label20, label25, 10);
        methodVisitor.visitLocalVariable("input", "Ljava/io/InputStream;", null, label3, label25, 11);
        methodVisitor.visitLocalVariable("b", "[B", null, label7, label27, 1);
        methodVisitor.visitLocalVariable("off", "I", null, label8, label27, 2);
        methodVisitor.visitLocalVariable("len", "I", null, label9, label27, 3);
        methodVisitor.visitLocalVariable("count", "I", null, label10, label27, 4);
        methodVisitor.visitLocalVariable("pos", "I", null, label11, label27, 5);
        methodVisitor.visitLocalVariable("buf", "[B", null, label12, label27, 6);
        methodVisitor.visitLocalVariable("in", "Ljava/io/InputStream;", null, label0, label27, 7);
        methodVisitor.visitLocalVariable("n", "I", null, label15, label27, 8);
        methodVisitor.visitMaxs(4, 13);
        methodVisitor.visitEnd();
    }
}
