package com.me.plugin.templates.add;

import static org.objectweb.asm.Opcodes.*;

import org.objectweb.asm.Handle;
import  org.objectweb.asm.Opcodes;

import org.objectweb.asm.Label;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Type;

public class Template7 {

    public static void  fillfromCode(MethodVisitor methodVisitor){
        methodVisitor.visitCode();
        Label label0 = new Label();
        methodVisitor.visitLabel(label0);
        methodVisitor.visitLineNumber(1283, label0);
        methodVisitor.visitLdcInsn("abcd");
        methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "java/lang/String", "getBytes", "()[B", false);
        methodVisitor.visitVarInsn(ASTORE, 0);
        Label label1 = new Label();
        methodVisitor.visitLabel(label1);
        methodVisitor.visitLineNumber(1284, label1);
        methodVisitor.visitInsn(ICONST_0);
        methodVisitor.visitVarInsn(ISTORE, 1);
        Label label2 = new Label();
        methodVisitor.visitLabel(label2);
        methodVisitor.visitLineNumber(1285, label2);
        methodVisitor.visitVarInsn(ALOAD, 0);
        methodVisitor.visitInsn(ARRAYLENGTH);
        methodVisitor.visitVarInsn(ISTORE, 2);
        Label label3 = new Label();
        methodVisitor.visitLabel(label3);
        methodVisitor.visitLineNumber(1286, label3);
        methodVisitor.visitInsn(ICONST_0);
        methodVisitor.visitVarInsn(ISTORE, 3);
        Label label4 = new Label();
        methodVisitor.visitLabel(label4);
        methodVisitor.visitLineNumber(1287, label4);
        methodVisitor.visitInsn(ICONST_0);
        methodVisitor.visitVarInsn(ISTORE, 4);
        Label label5 = new Label();
        methodVisitor.visitLabel(label5);
        methodVisitor.visitLineNumber(1288, label5);
        methodVisitor.visitInsn(ICONST_0);
        methodVisitor.visitVarInsn(ISTORE, 5);
        Label label6 = new Label();
        methodVisitor.visitLabel(label6);
        methodVisitor.visitLineNumber(1289, label6);
        methodVisitor.visitIntInsn(BIPUSH, 33);
        methodVisitor.visitIntInsn(NEWARRAY, T_INT);
        methodVisitor.visitInsn(DUP);
        methodVisitor.visitInsn(ICONST_0);
        methodVisitor.visitInsn(ICONST_0);
        methodVisitor.visitInsn(IASTORE);
        methodVisitor.visitInsn(DUP);
        methodVisitor.visitInsn(ICONST_1);
        methodVisitor.visitInsn(ICONST_1);
        methodVisitor.visitInsn(IASTORE);
        methodVisitor.visitInsn(DUP);
        methodVisitor.visitInsn(ICONST_2);
        methodVisitor.visitInsn(ICONST_3);
        methodVisitor.visitInsn(IASTORE);
        methodVisitor.visitInsn(DUP);
        methodVisitor.visitInsn(ICONST_3);
        methodVisitor.visitIntInsn(BIPUSH, 7);
        methodVisitor.visitInsn(IASTORE);
        methodVisitor.visitInsn(DUP);
        methodVisitor.visitInsn(ICONST_4);
        methodVisitor.visitIntInsn(BIPUSH, 15);
        methodVisitor.visitInsn(IASTORE);
        methodVisitor.visitInsn(DUP);
        methodVisitor.visitInsn(ICONST_5);
        methodVisitor.visitIntInsn(BIPUSH, 31);
        methodVisitor.visitInsn(IASTORE);
        methodVisitor.visitInsn(DUP);
        methodVisitor.visitIntInsn(BIPUSH, 6);
        methodVisitor.visitIntInsn(BIPUSH, 63);
        methodVisitor.visitInsn(IASTORE);
        methodVisitor.visitInsn(DUP);
        methodVisitor.visitIntInsn(BIPUSH, 7);
        methodVisitor.visitIntInsn(BIPUSH, 127);
        methodVisitor.visitInsn(IASTORE);
        methodVisitor.visitInsn(DUP);
        methodVisitor.visitIntInsn(BIPUSH, 8);
        methodVisitor.visitIntInsn(SIPUSH, 255);
        methodVisitor.visitInsn(IASTORE);
        methodVisitor.visitInsn(DUP);
        methodVisitor.visitIntInsn(BIPUSH, 9);
        methodVisitor.visitIntInsn(SIPUSH, 511);
        methodVisitor.visitInsn(IASTORE);
        methodVisitor.visitInsn(DUP);
        methodVisitor.visitIntInsn(BIPUSH, 10);
        methodVisitor.visitIntInsn(SIPUSH, 1023);
        methodVisitor.visitInsn(IASTORE);
        methodVisitor.visitInsn(DUP);
        methodVisitor.visitIntInsn(BIPUSH, 11);
        methodVisitor.visitIntInsn(SIPUSH, 2047);
        methodVisitor.visitInsn(IASTORE);
        methodVisitor.visitInsn(DUP);
        methodVisitor.visitIntInsn(BIPUSH, 12);
        methodVisitor.visitIntInsn(SIPUSH, 4095);
        methodVisitor.visitInsn(IASTORE);
        methodVisitor.visitInsn(DUP);
        methodVisitor.visitIntInsn(BIPUSH, 13);
        methodVisitor.visitIntInsn(SIPUSH, 8191);
        methodVisitor.visitInsn(IASTORE);
        methodVisitor.visitInsn(DUP);
        methodVisitor.visitIntInsn(BIPUSH, 14);
        methodVisitor.visitIntInsn(SIPUSH, 16383);
        methodVisitor.visitInsn(IASTORE);
        methodVisitor.visitInsn(DUP);
        methodVisitor.visitIntInsn(BIPUSH, 15);
        methodVisitor.visitIntInsn(SIPUSH, 32767);
        methodVisitor.visitInsn(IASTORE);
        methodVisitor.visitInsn(DUP);
        methodVisitor.visitIntInsn(BIPUSH, 16);
        methodVisitor.visitLdcInsn(new Integer(65535));
        methodVisitor.visitInsn(IASTORE);
        methodVisitor.visitInsn(DUP);
        methodVisitor.visitIntInsn(BIPUSH, 17);
        methodVisitor.visitLdcInsn(new Integer(131071));
        methodVisitor.visitInsn(IASTORE);
        methodVisitor.visitInsn(DUP);
        methodVisitor.visitIntInsn(BIPUSH, 18);
        methodVisitor.visitLdcInsn(new Integer(262143));
        methodVisitor.visitInsn(IASTORE);
        methodVisitor.visitInsn(DUP);
        methodVisitor.visitIntInsn(BIPUSH, 19);
        methodVisitor.visitLdcInsn(new Integer(524287));
        methodVisitor.visitInsn(IASTORE);
        methodVisitor.visitInsn(DUP);
        methodVisitor.visitIntInsn(BIPUSH, 20);
        methodVisitor.visitLdcInsn(new Integer(1048575));
        methodVisitor.visitInsn(IASTORE);
        methodVisitor.visitInsn(DUP);
        methodVisitor.visitIntInsn(BIPUSH, 21);
        methodVisitor.visitLdcInsn(new Integer(2097151));
        methodVisitor.visitInsn(IASTORE);
        methodVisitor.visitInsn(DUP);
        methodVisitor.visitIntInsn(BIPUSH, 22);
        methodVisitor.visitLdcInsn(new Integer(4194303));
        methodVisitor.visitInsn(IASTORE);
        methodVisitor.visitInsn(DUP);
        methodVisitor.visitIntInsn(BIPUSH, 23);
        methodVisitor.visitLdcInsn(new Integer(8388607));
        methodVisitor.visitInsn(IASTORE);
        methodVisitor.visitInsn(DUP);
        methodVisitor.visitIntInsn(BIPUSH, 24);
        methodVisitor.visitLdcInsn(new Integer(16777215));
        methodVisitor.visitInsn(IASTORE);
        methodVisitor.visitInsn(DUP);
        methodVisitor.visitIntInsn(BIPUSH, 25);
        methodVisitor.visitLdcInsn(new Integer(33554431));
        methodVisitor.visitInsn(IASTORE);
        methodVisitor.visitInsn(DUP);
        methodVisitor.visitIntInsn(BIPUSH, 26);
        methodVisitor.visitLdcInsn(new Integer(67108863));
        methodVisitor.visitInsn(IASTORE);
        methodVisitor.visitInsn(DUP);
        methodVisitor.visitIntInsn(BIPUSH, 27);
        methodVisitor.visitLdcInsn(new Integer(134217727));
        methodVisitor.visitInsn(IASTORE);
        methodVisitor.visitInsn(DUP);
        methodVisitor.visitIntInsn(BIPUSH, 28);
        methodVisitor.visitLdcInsn(new Integer(268435455));
        methodVisitor.visitInsn(IASTORE);
        methodVisitor.visitInsn(DUP);
        methodVisitor.visitIntInsn(BIPUSH, 29);
        methodVisitor.visitLdcInsn(new Integer(536870911));
        methodVisitor.visitInsn(IASTORE);
        methodVisitor.visitInsn(DUP);
        methodVisitor.visitIntInsn(BIPUSH, 30);
        methodVisitor.visitLdcInsn(new Integer(1073741823));
        methodVisitor.visitInsn(IASTORE);
        methodVisitor.visitInsn(DUP);
        methodVisitor.visitIntInsn(BIPUSH, 31);
        methodVisitor.visitLdcInsn(new Integer(2147483647));
        methodVisitor.visitInsn(IASTORE);
        methodVisitor.visitInsn(DUP);
        methodVisitor.visitIntInsn(BIPUSH, 32);
        methodVisitor.visitInsn(ICONST_M1);
        methodVisitor.visitInsn(IASTORE);
        methodVisitor.visitVarInsn(ASTORE, 6);
        Label label7 = new Label();
        methodVisitor.visitLabel(label7);
        methodVisitor.visitLineNumber(1299, label7);
        methodVisitor.visitLdcInsn(new Long(10L));
        methodVisitor.visitVarInsn(LSTORE, 7);
        Label label8 = new Label();
        methodVisitor.visitLabel(label8);
        methodVisitor.visitLineNumber(1300, label8);
        methodVisitor.visitInsn(ICONST_2);
        methodVisitor.visitVarInsn(ISTORE, 9);
        Label label9 = new Label();
        methodVisitor.visitLabel(label9);
        methodVisitor.visitLineNumber(1301, label9);
        methodVisitor.visitInsn(LCONST_0);
        methodVisitor.visitVarInsn(LSTORE, 10);
        Label label10 = new Label();
        methodVisitor.visitLabel(label10);
        methodVisitor.visitLineNumber(1302, label10);
        methodVisitor.visitIntInsn(BIPUSH, 8);
        methodVisitor.visitVarInsn(ISTORE, 12);
        Label label11 = new Label();
        methodVisitor.visitLabel(label11);
        methodVisitor.visitLineNumber(1304, label11);
        methodVisitor.visitVarInsn(ALOAD, 0);
        methodVisitor.visitInsn(ARRAYLENGTH);
        methodVisitor.visitIntInsn(NEWARRAY, T_BYTE);
        methodVisitor.visitVarInsn(ASTORE, 13);
        Label label12 = new Label();
        methodVisitor.visitLabel(label12);
        methodVisitor.visitLineNumber(1306, label12);
        methodVisitor.visitInsn(ICONST_0);
        methodVisitor.visitVarInsn(ISTORE, 14);
        Label label13 = new Label();
        methodVisitor.visitLabel(label13);
        methodVisitor.visitLineNumber(1308, label13);
        methodVisitor.visitVarInsn(ILOAD, 1);
        methodVisitor.visitVarInsn(ILOAD, 2);
        methodVisitor.visitInsn(IADD);
        methodVisitor.visitVarInsn(ISTORE, 15);
        Label label14 = new Label();
        methodVisitor.visitLabel(label14);
        methodVisitor.visitLineNumber(1309, label14);
        methodVisitor.visitInsn(ICONST_0);
        methodVisitor.visitVarInsn(ISTORE, 16);
        Label label15 = new Label();
        methodVisitor.visitLabel(label15);
        methodVisitor.visitLineNumber(1311, label15);
        methodVisitor.visitVarInsn(ILOAD, 3);
        methodVisitor.visitVarInsn(ISTORE, 17);
        Label label16 = new Label();
        methodVisitor.visitLabel(label16);
        methodVisitor.visitLineNumber(1313, label16);
        methodVisitor.visitFrame(Opcodes.F_NEW, 16, new Object[] {"[B", Opcodes.INTEGER, Opcodes.INTEGER, Opcodes.INTEGER, Opcodes.INTEGER, Opcodes.INTEGER, "[I", Opcodes.LONG, Opcodes.INTEGER, Opcodes.LONG, Opcodes.INTEGER, "[B", Opcodes.INTEGER, Opcodes.INTEGER, Opcodes.INTEGER, Opcodes.INTEGER}, 0, new Object[] {});
        methodVisitor.visitVarInsn(ILOAD, 1);
        methodVisitor.visitVarInsn(ILOAD, 15);
        Label label17 = new Label();
        methodVisitor.visitJumpInsn(IF_ICMPGE, label17);
        Label label18 = new Label();
        methodVisitor.visitLabel(label18);
        methodVisitor.visitLineNumber(1316, label18);
        methodVisitor.visitVarInsn(ALOAD, 0);
        methodVisitor.visitVarInsn(ILOAD, 1);
        methodVisitor.visitIincInsn(1, 1);
        methodVisitor.visitInsn(BALOAD);
        methodVisitor.visitIntInsn(SIPUSH, 255);
        methodVisitor.visitInsn(IAND);
        methodVisitor.visitInsn(I2L);
        methodVisitor.visitVarInsn(LSTORE, 10);
        Label label19 = new Label();
        methodVisitor.visitLabel(label19);
        methodVisitor.visitLineNumber(1318, label19);
        methodVisitor.visitVarInsn(LLOAD, 7);
        methodVisitor.visitVarInsn(LLOAD, 10);
        methodVisitor.visitVarInsn(ILOAD, 9);
        methodVisitor.visitInsn(LSHL);
        methodVisitor.visitInsn(LOR);
        methodVisitor.visitVarInsn(LSTORE, 7);
        Label label20 = new Label();
        methodVisitor.visitLabel(label20);
        methodVisitor.visitLineNumber(1320, label20);
        methodVisitor.visitIincInsn(9, 8);
        Label label21 = new Label();
        methodVisitor.visitLabel(label21);
        methodVisitor.visitLineNumber(1322, label21);
        methodVisitor.visitVarInsn(ILOAD, 3);
        methodVisitor.visitVarInsn(ILOAD, 12);
        methodVisitor.visitInsn(ISUB);
        methodVisitor.visitVarInsn(ISTORE, 17);
        Label label22 = new Label();
        methodVisitor.visitLabel(label22);
        methodVisitor.visitLineNumber(1323, label22);
        methodVisitor.visitVarInsn(ALOAD, 13);
        methodVisitor.visitVarInsn(ILOAD, 16);
        methodVisitor.visitInsn(DUP2);
        methodVisitor.visitInsn(BALOAD);
        methodVisitor.visitInsn(ICONST_0);
        methodVisitor.visitInsn(IOR);
        methodVisitor.visitInsn(I2B);
        methodVisitor.visitInsn(BASTORE);
        Label label23 = new Label();
        methodVisitor.visitLabel(label23);
        methodVisitor.visitLineNumber(1325, label23);
        methodVisitor.visitFrame(Opcodes.F_NEW, 16, new Object[] {"[B", Opcodes.INTEGER, Opcodes.INTEGER, Opcodes.INTEGER, Opcodes.INTEGER, Opcodes.INTEGER, "[I", Opcodes.LONG, Opcodes.INTEGER, Opcodes.LONG, Opcodes.INTEGER, "[B", Opcodes.INTEGER, Opcodes.INTEGER, Opcodes.INTEGER, Opcodes.INTEGER}, 0, new Object[] {});
        methodVisitor.visitVarInsn(ILOAD, 17);
        methodVisitor.visitIntInsn(BIPUSH, 8);
        Label label24 = new Label();
        methodVisitor.visitJumpInsn(IF_ICMPGE, label24);
        Label label25 = new Label();
        methodVisitor.visitLabel(label25);
        methodVisitor.visitLineNumber(1326, label25);
        methodVisitor.visitVarInsn(ALOAD, 13);
        methodVisitor.visitIincInsn(16, 1);
        methodVisitor.visitVarInsn(ILOAD, 16);
        methodVisitor.visitInsn(DUP2);
        methodVisitor.visitInsn(BALOAD);
        methodVisitor.visitInsn(I2L);
        methodVisitor.visitVarInsn(LLOAD, 7);
        methodVisitor.visitVarInsn(ILOAD, 17);
        methodVisitor.visitIntInsn(BIPUSH, 8);
        methodVisitor.visitInsn(ISUB);
        methodVisitor.visitInsn(LSHR);
        methodVisitor.visitVarInsn(ALOAD, 6);
        methodVisitor.visitIntInsn(BIPUSH, 8);
        methodVisitor.visitInsn(IALOAD);
        methodVisitor.visitInsn(I2L);
        methodVisitor.visitInsn(LAND);
        methodVisitor.visitInsn(LOR);
        methodVisitor.visitInsn(L2I);
        methodVisitor.visitInsn(I2B);
        methodVisitor.visitInsn(BASTORE);
        Label label26 = new Label();
        methodVisitor.visitLabel(label26);
        methodVisitor.visitLineNumber(1327, label26);
        methodVisitor.visitIincInsn(17, 8);
        methodVisitor.visitJumpInsn(GOTO, label23);
        methodVisitor.visitLabel(label24);
        methodVisitor.visitLineNumber(1330, label24);
        methodVisitor.visitFrame(Opcodes.F_NEW, 16, new Object[] {"[B", Opcodes.INTEGER, Opcodes.INTEGER, Opcodes.INTEGER, Opcodes.INTEGER, Opcodes.INTEGER, "[I", Opcodes.LONG, Opcodes.INTEGER, Opcodes.LONG, Opcodes.INTEGER, "[B", Opcodes.INTEGER, Opcodes.INTEGER, Opcodes.INTEGER, Opcodes.INTEGER}, 0, new Object[] {});
        methodVisitor.visitVarInsn(ALOAD, 13);
        methodVisitor.visitIincInsn(16, 1);
        methodVisitor.visitVarInsn(ILOAD, 16);
        methodVisitor.visitInsn(DUP2);
        methodVisitor.visitInsn(BALOAD);
        methodVisitor.visitInsn(I2L);
        methodVisitor.visitVarInsn(LLOAD, 7);
        methodVisitor.visitVarInsn(ALOAD, 6);
        methodVisitor.visitVarInsn(ILOAD, 17);
        methodVisitor.visitInsn(IALOAD);
        methodVisitor.visitInsn(I2L);
        methodVisitor.visitInsn(LAND);
        methodVisitor.visitIntInsn(BIPUSH, 8);
        methodVisitor.visitVarInsn(ILOAD, 17);
        methodVisitor.visitInsn(ISUB);
        methodVisitor.visitInsn(LSHL);
        methodVisitor.visitInsn(LOR);
        methodVisitor.visitInsn(L2I);
        methodVisitor.visitInsn(I2B);
        methodVisitor.visitInsn(BASTORE);
        Label label27 = new Label();
        methodVisitor.visitLabel(label27);
        methodVisitor.visitLineNumber(1331, label27);
        methodVisitor.visitIincInsn(17, -8);
        Label label28 = new Label();
        methodVisitor.visitLabel(label28);
        methodVisitor.visitLineNumber(1333, label28);
        methodVisitor.visitVarInsn(ILOAD, 3);
        methodVisitor.visitVarInsn(ISTORE, 17);
        Label label29 = new Label();
        methodVisitor.visitLabel(label29);
        methodVisitor.visitLineNumber(1334, label29);
        methodVisitor.visitVarInsn(ALOAD, 13);
        methodVisitor.visitVarInsn(ILOAD, 16);
        methodVisitor.visitInsn(DUP2);
        methodVisitor.visitInsn(BALOAD);
        methodVisitor.visitInsn(I2L);
        methodVisitor.visitVarInsn(LLOAD, 7);
        methodVisitor.visitVarInsn(ALOAD, 6);
        methodVisitor.visitVarInsn(ILOAD, 12);
        methodVisitor.visitInsn(IALOAD);
        methodVisitor.visitInsn(I2L);
        methodVisitor.visitInsn(LAND);
        methodVisitor.visitInsn(ICONST_1);
        methodVisitor.visitInsn(LSHL);
        methodVisitor.visitInsn(LOR);
        methodVisitor.visitInsn(L2I);
        methodVisitor.visitInsn(I2B);
        methodVisitor.visitInsn(BASTORE);
        Label label30 = new Label();
        methodVisitor.visitLabel(label30);
        methodVisitor.visitLineNumber(1335, label30);
        methodVisitor.visitVarInsn(LLOAD, 7);
        methodVisitor.visitVarInsn(ILOAD, 12);
        methodVisitor.visitInsn(LSHR);
        methodVisitor.visitVarInsn(LSTORE, 7);
        Label label31 = new Label();
        methodVisitor.visitLabel(label31);
        methodVisitor.visitLineNumber(1336, label31);
        methodVisitor.visitVarInsn(ILOAD, 17);
        methodVisitor.visitVarInsn(ILOAD, 12);
        methodVisitor.visitInsn(ISUB);
        methodVisitor.visitVarInsn(ISTORE, 17);
        Label label32 = new Label();
        methodVisitor.visitLabel(label32);
        methodVisitor.visitLineNumber(1339, label32);
        methodVisitor.visitVarInsn(ALOAD, 13);
        methodVisitor.visitIincInsn(16, 1);
        methodVisitor.visitVarInsn(ILOAD, 16);
        methodVisitor.visitInsn(DUP2);
        methodVisitor.visitInsn(BALOAD);
        methodVisitor.visitInsn(I2L);
        methodVisitor.visitVarInsn(LLOAD, 7);
        methodVisitor.visitLdcInsn(new Long(255L));
        methodVisitor.visitInsn(LAND);
        methodVisitor.visitInsn(LOR);
        methodVisitor.visitInsn(L2I);
        methodVisitor.visitInsn(I2B);
        methodVisitor.visitInsn(BASTORE);
        Label label33 = new Label();
        methodVisitor.visitLabel(label33);
        methodVisitor.visitLineNumber(1340, label33);
        methodVisitor.visitVarInsn(LLOAD, 7);
        methodVisitor.visitIntInsn(BIPUSH, 8);
        methodVisitor.visitInsn(LSHR);
        methodVisitor.visitVarInsn(LSTORE, 7);
        Label label34 = new Label();
        methodVisitor.visitLabel(label34);
        methodVisitor.visitLineNumber(1341, label34);
        methodVisitor.visitIincInsn(17, -8);
        Label label35 = new Label();
        methodVisitor.visitLabel(label35);
        methodVisitor.visitLineNumber(1344, label35);
        methodVisitor.visitVarInsn(ALOAD, 13);
        methodVisitor.visitIincInsn(16, 1);
        methodVisitor.visitVarInsn(ILOAD, 16);
        methodVisitor.visitInsn(DUP2);
        methodVisitor.visitInsn(BALOAD);
        methodVisitor.visitInsn(I2L);
        methodVisitor.visitVarInsn(LLOAD, 7);
        methodVisitor.visitVarInsn(ALOAD, 6);
        methodVisitor.visitVarInsn(ILOAD, 17);
        methodVisitor.visitInsn(IALOAD);
        methodVisitor.visitInsn(I2L);
        methodVisitor.visitInsn(LAND);
        methodVisitor.visitInsn(LOR);
        methodVisitor.visitInsn(L2I);
        methodVisitor.visitInsn(I2B);
        methodVisitor.visitInsn(BASTORE);
        Label label36 = new Label();
        methodVisitor.visitLabel(label36);
        methodVisitor.visitLineNumber(1345, label36);
        methodVisitor.visitIincInsn(17, -8);
        Label label37 = new Label();
        methodVisitor.visitLabel(label37);
        methodVisitor.visitLineNumber(1348, label37);
        methodVisitor.visitVarInsn(ILOAD, 17);
        methodVisitor.visitInsn(INEG);
        methodVisitor.visitVarInsn(ISTORE, 12);
        Label label38 = new Label();
        methodVisitor.visitLabel(label38);
        methodVisitor.visitLineNumber(1350, label38);
        methodVisitor.visitIincInsn(14, 1);
        methodVisitor.visitVarInsn(ILOAD, 14);
        methodVisitor.visitVarInsn(ILOAD, 4);
        methodVisitor.visitInsn(IREM);
        methodVisitor.visitJumpInsn(IFNE, label16);
        Label label39 = new Label();
        methodVisitor.visitLabel(label39);
        methodVisitor.visitLineNumber(1351, label39);
        methodVisitor.visitInsn(ICONST_0);
        methodVisitor.visitVarInsn(ISTORE, 12);
        Label label40 = new Label();
        methodVisitor.visitLabel(label40);
        methodVisitor.visitLineNumber(1352, label40);
        methodVisitor.visitInsn(ICONST_0);
        methodVisitor.visitVarInsn(ISTORE, 9);
        methodVisitor.visitJumpInsn(GOTO, label16);
        methodVisitor.visitLabel(label17);
        methodVisitor.visitLineNumber(1357, label17);
        methodVisitor.visitFrame(Opcodes.F_NEW, 16, new Object[] {"[B", Opcodes.INTEGER, Opcodes.INTEGER, Opcodes.INTEGER, Opcodes.INTEGER, Opcodes.INTEGER, "[I", Opcodes.LONG, Opcodes.INTEGER, Opcodes.LONG, Opcodes.INTEGER, "[B", Opcodes.INTEGER, Opcodes.INTEGER, Opcodes.INTEGER, Opcodes.INTEGER}, 0, new Object[] {});
        methodVisitor.visitInsn(RETURN);
        Label label41 = new Label();
        methodVisitor.visitLabel(label41);
        methodVisitor.visitLocalVariable("input", "[B", null, label1, label41, 0);
        methodVisitor.visitLocalVariable("offset", "I", null, label2, label41, 1);
        methodVisitor.visitLocalVariable("len", "I", null, label3, label41, 2);
        methodVisitor.visitLocalVariable("bits", "I", null, label4, label41, 3);
        methodVisitor.visitLocalVariable("scanLineStride", "I", null, label5, label41, 4);
        methodVisitor.visitLocalVariable("bigEndian", "Z", null, label6, label41, 5);
        methodVisitor.visitLocalVariable("MASK", "[I", null, label7, label41, 6);
        methodVisitor.visitLocalVariable("value", "J", null, label8, label41, 7);
        methodVisitor.visitLocalVariable("bits_remain", "I", null, label9, label41, 9);
        methodVisitor.visitLocalVariable("temp_byte", "J", null, label10, label41, 10);
        methodVisitor.visitLocalVariable("empty_bits", "I", null, label11, label41, 12);
        methodVisitor.visitLocalVariable("output", "[B", null, label12, label41, 13);
        methodVisitor.visitLocalVariable("strideCounter", "I", null, label13, label41, 14);
        methodVisitor.visitLocalVariable("end", "I", null, label14, label41, 15);
        methodVisitor.visitLocalVariable("bufIndex", "I", null, label15, label41, 16);
        methodVisitor.visitLocalVariable("temp", "I", null, label16, label41, 17);
        methodVisitor.visitMaxs(8, 18);
        methodVisitor.visitEnd();
    }
}
